### ISSUE TITLE
vectorizing_text.ipynb Cell #4 error

### ISSUE THREAD

**Issue by SSJUSA** [hundredblocks/ml-powered-applications#10]
On my Windows 10 laptop with GPU, out of 15 notebook python files of this book, 14 completed successfully without errors. One program vectorizing_text.ipynb is giving error message "Kernel Restarting. Kernel appears to have died. It will restart automatically".

It dies on cell 4, 
umap_embedder = umap.UMAP()
umap_bow = umap_embedder.fit_transform(bag_of_words)

Is this error due to less RAM memory on my laptop? 
Any suggestions or workarounds to fix this error please? Thanks.

Can this program be run by lowering size of bag_of_words?

How to estimate memory requirements of a notebook program file?

My PC has Intel i7-9750H CPU @ 2.60 GHz and
NVIDIA GeForce RTX 2070 with Max-Q Design, RAM 16 GB 

What kind of hardware you have used to test these programs? 
How much RAM memory you have on your computer?

Is it a UNIX system computer?

I have UNIX on a basic very low clock speed laptop, (no GPU). 
I don't think it will work. 
I do not know how to setup my unix (Ubantu 18.4) laptop for Machine Learning use.

Any suggestions to get this program working please?

Thanks,
SSJ

**Comment by hundredblocks** [comment]
Thank you for reporting the error @SSJUSA. While UMAP claims to be pretty memory efficient (see their [benchmark](https://umap-learn.readthedocs.io/en/latest/performance.html)), it can still get pretty memory hungry!

To get the notebook running, I suggest switching to a faster embedding method. Here, [TruncatedSVD](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html) should do the trick.

To use that, replace cell 4 with:
```
from sklearn.decomposition import TruncatedSVD
umap_embedder = TruncatedSVD()
umap_bow = umap_embedder.fit_transform(bag_of_words)
```

You will likely also need to change cell 8 to use `TruncatedSVD` by replacing it with:

```
umap_embedder = TruncatedSVD()
umap_emb = umap_embedder.fit_transform(embeddings)
```

If that does not fix your issue, you can instead reduce the dataset size by selecting the first 2000 rows for example. To do so, add a new line in the first cell following the `format_raw_df` call:
`df = df.head(2000)`

**Comment by SSJUSA** [comment]
Thank you very much for code fixes.

I made code changes and I got following Cell #8 errors:

umap_embedder = TruncatedSVD()
umap_emb = umap_embedder.fit_transform(embeddings)


ValueError                                Traceback (most recent call
last)<ipython-input-8-33a3c30abbdb> in <module>      3       4
umap_embedder = TruncatedSVD()----> 5 umap_emb =
umap_embedder.fit_transform(embeddings)
C:\ProgramData\Anaconda3\envs\tf_SSJ_gpu\lib\site-packages\sklearn\decomposition\_truncated_svd.py
in fit_transform(self, X, y)    160         """    161         X =
check_array(X, accept_sparse=['csr', 'csc'],--> 162
     ensure_min_features=2)    163         random_state =
check_random_state(self.random_state)    164
C:\ProgramData\Anaconda3\envs\tf_SSJ_gpu\lib\site-packages\sklearn\utils\validation.py
in check_array(array, accept_sparse, accept_large_sparse, dtype,
order, copy, force_all_finite, ensure_2d, allow_nd,
ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
592                              " a minimum of %d is required%s."
593                              % (n_features, array.shape,
ensure_min_features,--> 594                                 context))
  595     596     if warn_on_dtype and dtype_orig is not None and
array.dtype != dtype_orig:
ValueError: Found array with 0 feature(s) (shape=(5676, 0)) while a
minimum of 2 is required.

**Comment by hundredblocks** [comment]
The error `ValueError: Found array with 0 feature(s) (shape=(5676, 0)) while a
minimum of 2 is required.` makes it seem like the `embeddings` variable has rows of size 0. I think this may be a different issue than the previous one.

If you run `embeddings.shape` in a notebook cell right before cell 8 should be able to see whether they are of the correct size. On the full dataset, the results should be `(5676, 300)`. If you've run `df = df.head(2000)` it should be `(265, 300)`. 

If they are not, try running `train_author[train_author["is_question"]]["body_text"].shape` which should be the same number of rows (but only one dimension). So for the full dataset you should see `(5676,)` and `(265,)` for the partial one. 

Finally, you may want to take another look at the spaCy [docs](https://spacy.io/models/en#en_core_web_lg) and reinstall the large model by running `python -m spacy download en_core_web_lg` from the command line.

**Comment by SSJUSA** [comment]
Thank you very much for the excellent information.
This notebook is running without errors.

Best regards,
SSJ

**Comment by SSJUSA** [comment]
This is resolved quickly by the author @hundredblocks . Thanks.
This is closed.
