### ISSUE TITLE
ImportError: cannot import name 'joblib' from 'sklearn.externals',  ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by JvGar28** [hundredblocks/ml-powered-applications#12]
Not sure if I have to update something, but I am currently having an issue running the code within the "Training a simple model" notebook. It is specifically with importing joblib. When I ran the code initially how it is set up, I get the first error listed above. (Note: the notebook currently imports with "from sklearn.externals import joblib"). So I rewrote the line to "import joblib" and get the second error above. Not sure what to do from here.

**Comment by JvGar28** [comment]
It had something to do with my jupyter notebook. I just refreshed the page and the errors went away.

**Comment by hundredblocks** [comment]
Glad you managed to find a fix!
