### ISSUE TITLE
Can't run pip install -r requirements.txt

### ISSUE THREAD

**Issue by iamjackhu** [hundredblocks/ml-powered-applications#30]
Could you please provide a docker image, which has installed all the dependencies of this app, to run your sample code? 

It always shows many types of dependencies error when we are preparing the run environments.

**Comment by hundredblocks** [comment]
I’m sorry you are having issues. The requirements file should install the necessary packages, which issues are you encountering?

**Comment by iamjackhu** [comment]
yes, I initial the env with pip install -r requirements. But it reports many errors, such as:
`Collecting matplotlib==3.0.3
  Using cached https://mirrors.aliyun.com/pypi/packages/26/04/8b381d5b166508cc258632b225adbafec49bbe69aa9a4fa1f1b461428313/matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zanu5_as/matplotlib_2e4e6a9fbcbc467c99ec43ae9cb63e48/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-zanu5_as/matplotlib_2e4e6a9fbcbc467c99ec43ae9cb63e48/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      IMPORTANT WARNING:
          pkg-config is not installed.
          matplotlib may not be able to find some of its dependencies
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.10.12 (main, Jun 11 2023, 05:26:28) [GCC
                              11.4.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.25.1]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

**Comment by hundredblocks** [comment]
I see. Unfortunately I cannot provide a docker image at the moment but can help you debug in this thread. In this case it looks like the version of `matplotlib` that is requires is too old and relying on a deprecated package. You can fix this by unpinning the dependency and running `pip install matplotlib`.

**Comment by xingvoong** [comment]
I can't run the requirement.txt file either.

My error message:
`error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k`

**Comment by hundredblocks** [comment]
@xingvoong this sounds like a different issue. The `requirements.txt` file does not [include](https://github.com/hundredblocks/ml-powered-applications/blob/master/requirements.txt) a `pytz` package, so I'm assuming this is an error in the `pandas` version. I'd try the same thing I recommended above, and run `pip install pandas`
