### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by mjburgess** [hundredblocks/ml-powered-applications#8]
Hello,

Would you mind adding a licence to this project code?

Personally I'm not going to use it directly for anything, but it might be a good starter for a project and without a licence i'd hesitate to use it for that purpose. 

Apache 2, MIT, CC-BY-SA, etc. would be great. 

Thanks

**Comment by hundredblocks** [comment]
I was certain that I already had, thank you for catching my oversight!

MIT License added here: https://github.com/hundredblocks/ml-powered-applications/blob/master/LICENSE.md
